### ISSUE TITLE
PA9 and its 3-pin connector

### ISSUE THREAD

**Issue by GreenCapMan** [KoBussLLC/grabert-hardware#2]
Hi there,

I come here from your youtube channel and I want to make PCB for single hand keyboard. I was trying to copy your design idea. I found that you had a connector with Vcc, ground, and PA9, of which the usage is not explained in your video. What is the purpose  of this connector? Is it for debug for the PCB when you received from the manufacturer?

BTW, very nice video and cute cats XD

Thanks a lot

**Comment by camrbuss** [comment]
It could be used for anything, leds, another screen, or powering something else.
